[package]
name = "dotnetcacheloadtestrustapi"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-beta.8"
redis = { version = "0.23.0", features = ["tokio-comp"] }
tokio = { version = "1", features = ["full"] }