version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: DotNetCacheLoadTest.WebApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - REDIS_CONNECTION=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
